# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L
  

# SEO

marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: ''
    description: 'Python pour les data scientists - Lino Galiana - Cours ENSAE 2e année (M1)'
    twitter: 'linogaliana'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© Lino Galiana. This work is licensed under Creative Commons Attribution-NonCommercial 4.0 International License'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
commentable: true

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - python
      - latex
    theme_light: monokai
    theme_dark: monokailight
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/linogaliana/python-datascientist'
    content_dir: content
    branch: master
  comment:
    # Choose a provider: giscus, disqus, commento, or '' to disable commenting
    provider: 'giscus'
    giscus:
      repo: 'linogaliana/python-datascientist'
      repo_id: 'MDEwOlJlcG9zaXRvcnkyODAxNjE2Nzc='
      category: 'Q&A'
      category_id: 'DIC_kwDOELLtjc4B-5TY'
      theme: preferred_color_scheme
      language_code: en
      mapping: pathname
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
