baseurl = "/"
DefaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "Python pour un data scientist/economist"
theme="hugo-theme-techdoc"
enableGitInfo = true
enableEmoji = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html"]

disableToc = false

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Manipuler des données"
        url = "/manipulation"
        weight = 2        
        
    [[menu.main]]
        name = "Visualiser des données"
        url = "/visualisation"
        weight = 3        

    [[menu.main]]
        name = "Modéliser"
        url = "/modelisation"
        weight = 4        


    [[menu.main]]
        name = "Git"
        url = "/git"
        weight = 5        

        
    [[menu.main]]
        name = "Evaluation"
        url = "/evaluation"
        weight = 6

    [[menu.main]]
        name = "Travaux dirigés"
        url = "/listeTP"
        weight = 7
        
    [[menu.main]]
        name = "References"
        url = "/references"
        weight = 8

    [[menu.main]]
        name = "Github"
        url = "https://github.com/linogaliana/python-datascientist"
        weight = 9

[params]
    # Source Code repository section
    description = "Lino Galiana"
    github_repository = "https://github.com/linogaliana/python-datascientist"
    # version = "0.9.2"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/linogaliana/python-datascientist"

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"