channels:
  - conda-forge

dependencies:
  - python
  - GDAL
  - bs4
  - contextily
  - dash
  - descartes
  - folium
  - geopandas
  - geoplot
  - jupyter
  - jupytext
  - keras
  - matplotlib
  - nbconvert
  - nltk
  - numpy
  - pandas
  - plotly
  - pyLDAvis
  - pywaffle
  - rasterio
  - requests
  - rtree
  - scipy
  - seaborn
  - tensorflow
  - wordcloud
  - xlrd
  - yellowbrick