channels:
  - conda-forge

dependencies:
  - python
  - GDAL
  - bs4
  - contextily
  - descartes
  - folium
  - geopandas
  - geoplot
  - jupyter
  - jupytext
  - matplotlib
  - nbconvert
  - numpy
  - pandas
  - plotly
  - python
  - rasterio
  - requests
  - rtree
  - scipy
  - seaborn