[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.95.0"
HUGO_ENABLEGITINFO = "true"

# [context]
# [context.branch-deploy]
# command = "hugo -F -b $DEPLOY_PRIME_URL"
# [context.deploy-preview]
# command = "hugo -F -b $DEPLOY_PRIME_URL"
# [context.production]
# [context.production.environment]
# HUGO_ENV = "production"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
