name: Test Python scripts on simplest ubuntu setting

on: [pull_request]


# example borrowed from https://pythonpackaging.info/06-Continuous-Integration.html
# and https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
# and https://autobencoder.com/2020-08-24-conda-actions/

jobs:
  build:

    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:latest

    steps:
      - uses: actions/checkout@v2
      - name: Test it
        run: |
          chmod u+x ./test.sh
          ./test.sh true "Rmd"