name: Test Python scripts on simplest ubuntu setting

on:
  pull_request:
    branches:
      - main
      - master
# un script plus leger pour faciliter les tests


# example borrowed from https://pythonpackaging.info/06-Continuous-Integration.html
# and https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
# and https://autobencoder.com/2020-08-24-conda-actions/

jobs:
  build:
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Test it
        run: |
         sudo rm -rf "./temp"
         sudo mkdir -p temp
         python cleanmd.py
         pip install jupytext
         cd ./temp
         for i in $(find . -type f \( -iname "*.md" -o -iname "*.Rmd" \)); do \
            echo "Converting $i" \
            # jupytext --to py --execute "$i"
            jupytext --to ipynb "$i" \
            rm $i \
         done
         rm 
      - uses: actions/upload-artifact@v1
        with:
          name: Notebooks
          path: temp/
